### ISSUE TITLE
the dates/years below the tear sheets are not printed 

### ISSUE THREAD

**Issue by carstenf** [stefan-jansen/pyfolio-reloaded#1]
I'm using MacOs 11.2.3
I'm using Python 3.8

using create_returns_tear_sheet
the dates/years below the tear sheets are not printed.
I do not get any warnings or errors.

This is a known issue with the original Pyfolio with python 3.6 (and zipline 1.4)

Could this be fixed in the future?

**Comment by stefan-jansen** [comment]
I'll take a look next week, sorry for the delay. Pull requests are welcome, of course.

**Comment by MBounouar** [comment]
The issue, as mentioned in an old zipline comment [#672](https://github.com/quantopian/pyfolio/issues/672) is due to the plots sharing the sharex=ax_rolling_returns. A quick fix would be to remove these. 
However,  at the slides (number 11) in 
[slides quantopian](https://nbviewer.jupyter.org/format/slides/github/quantopian/pyfolio/blob/master/pyfolio/examples/pyfolio_talk_slides.ipynb#/) this "issue" has been there for quite some time.
Also, looking at the matplotlib documentation I don't think that the intent is wrong. Unfortunately I don't have much time at the moment to investigate more.

**Comment by stefan-jansen** [comment]
Should be resolved thanks to [PR](https://github.com/stefan-jansen/pyfolio-reloaded/pull/3) by @MBounouar - pls feel free to reopen if that's not the case.
