### ISSUE TITLE
Pyfolio export output

### ISSUE THREAD

**Issue by Tigran79** [stefan-jansen/pyfolio-reloaded#16]
Hello,

 Can you please tell me how to save and export the output of pyfolio. For example  how to export pifolio.show_perf_stats(df)  or  pifolio.show_worst_drawdown_periods(df). When i try to  export pyfolio.export create_returns_tear_sheet report does not include portfolio metrics.

Thank you in advance,
Tigran Apoyan

**Comment by stefan-jansen** [comment]
The library including `pyfolio.show_perf_stats(df)` is designed for notebook display. You could modify a local version to save to csv instead of calling utils.print_table in [that function](https://github.com/stefan-jansen/pyfolio-reloaded/blob/71ab79b29bfd1721d3dc6dc8e18fed6c7b56c65f/src/pyfolio/plotting.py#L542), for instance.
